In [2]:
import keras
keras.__version__

import os, shutil

# The path to the directory where the original
# dataset was uncompressed
original_dataset_dir = 'train'

# The directory where we will
# store our smaller dataset
base_dir = 'data2'
os.mkdir(base_dir)

# Directories for our training,
# validation and test splits
train_dir = os.path.join(base_dir, 'train')
os.mkdir(train_dir)
validation_dir = os.path.join(base_dir, 'validation')
os.mkdir(validation_dir)
test_dir = os.path.join(base_dir, 'test')
os.mkdir(test_dir)

# Directory with our training cat pictures
train_cats_dir = os.path.join(train_dir, 'cats')
os.mkdir(train_cats_dir)

# Directory with our training dog pictures
train_dogs_dir = os.path.join(train_dir, 'dogs')
os.mkdir(train_dogs_dir)

# Directory with our validation cat pictures
validation_cats_dir = os.path.join(validation_dir, 'cats')
os.mkdir(validation_cats_dir)

# Directory with our validation dog pictures
validation_dogs_dir = os.path.join(validation_dir, 'dogs')
os.mkdir(validation_dogs_dir)

# Directory with our validation cat pictures
test_cats_dir = os.path.join(test_dir, 'cats')
os.mkdir(test_cats_dir)

# Directory with our validation dog pictures
test_dogs_dir = os.path.join(test_dir, 'dogs')
os.mkdir(test_dogs_dir)

# Copy first 1000 cat images to train_cats_dir
fnames = ['cat.{}.jpg'.format(i) for i in range(1000)]
for fname in fnames:
    src = os.path.join(original_dataset_dir, fname)
    dst = os.path.join(train_cats_dir, fname)
    shutil.copyfile(src, dst)

# Copy next 500 cat images to validation_cats_dir
fnames = ['cat.{}.jpg'.format(i) for i in range(1000, 1500)]
for fname in fnames:
    src = os.path.join(original_dataset_dir, fname)
    dst = os.path.join(validation_cats_dir, fname)
    shutil.copyfile(src, dst)
    
# Copy next 500 cat images to test_cats_dir
fnames = ['cat.{}.jpg'.format(i) for i in range(1500, 2000)]
for fname in fnames:
    src = os.path.join(original_dataset_dir, fname)
    dst = os.path.join(test_cats_dir, fname)
    shutil.copyfile(src, dst)
    
# Copy first 1000 dog images to train_dogs_dir
fnames = ['dog.{}.jpg'.format(i) for i in range(1000)]
for fname in fnames:
    src = os.path.join(original_dataset_dir, fname)
    dst = os.path.join(train_dogs_dir, fname)
    shutil.copyfile(src, dst)
    
# Copy next 500 dog images to validation_dogs_dir
fnames = ['dog.{}.jpg'.format(i) for i in range(1000, 1500)]
for fname in fnames:
    src = os.path.join(original_dataset_dir, fname)
    dst = os.path.join(validation_dogs_dir, fname)
    shutil.copyfile(src, dst)
    
# Copy next 500 dog images to test_dogs_dir
fnames = ['dog.{}.jpg'.format(i) for i in range(1500, 2000)]
for fname in fnames:
    src = os.path.join(original_dataset_dir, fname)
    dst = os.path.join(test_dogs_dir, fname)
    shutil.copyfile(src, dst)

In [3]:
print('total training cat images:', len(os.listdir(train_cats_dir)))
print('total training dog images:', len(os.listdir(train_dogs_dir)))
print('total validation cat images:', len(os.listdir(validation_cats_dir)))
print('total validation dog images:', len(os.listdir(validation_dogs_dir)))
print('total test cat images:', len(os.listdir(test_cats_dir)))
print('total test dog images:', len(os.listdir(test_dogs_dir)))

('total training cat images:', 1000)
('total training dog images:', 1000)
('total validation cat images:', 500)
('total validation dog images:', 500)
('total test cat images:', 500)
('total test dog images:', 500)


In [29]:
from keras.preprocessing.image import ImageDataGenerator

# All images will be rescaled by 1./255
train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        # This is the target directory
        train_dir,
        # All images will be resized to 150x150
        target_size=(150, 150),
        batch_size=20,
        # Since we use binary_crossentropy loss, we need binary labels
        class_mode=None)

validation_generator = test_datagen.flow_from_directory(
        validation_dir,
        target_size=(150, 150),
        batch_size=20,
        class_mode=None)

Found 2000 images belonging to 2 classes.
Found 1000 images belonging to 2 classes.


In [4]:
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', include_top=False)

58900480/58889256 [==============================] - 6s 0us/step


In [25]:
model= keras.applications.vgg16.VGG16(include_top=False, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=2)


In [26]:
from keras import optimizers

model.compile(loss='binary_crossentropy',
              optimizer=optimizers.SGD(lr=0.01, momentum=0.0, decay=0.0, nesterov=False),
              metrics=['acc'])

In [30]:
model.fit(train_generator, validation_data=validation_generator)
    


# Score trained model.
scores = model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', scores[0])
print('Test accuracy:', scores[1])

import matplotlib.pyplot as plt

acc = model.history.history['accuracy']
val_acc = model.history.history['val_accuracy']
loss = model.history.history['loss']
val_loss = model.history.history['val_loss']


epochs=range(1,len(loss)+1)
plt.plot(epochs,loss,'bo',label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.figure()



plt.plot(epochs,acc,'bo',label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Acc')
plt.legend()
plt.show()



Epoch 1/1


ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [[[[0.63529414 0.57254905 0.5137255 ]
   [0.63529414 0.57254905 0.5137255 ]
   [0.63529414 0.57254905 0.5137255 ]
   ...
   [0.22352943 0.21960786 0.20000002]
   [0.21960786 0.21568629 0.19607845]
   [0.21568629 0.21176472 0.19215688]]

  [[0.63529414 0.57254905 0.5137255 ]
   [0.63529414 0.57254905 0.5137255 ]
   [0.63529414 0.57254905 0.5137255 ]
   ...
   [0.19607845 0.20000002 0.1764706 ]
   [0.19607845 0.20000002 0.1764706 ]
   [0.19607845 0.20000002 0.1764706 ]]

  [[0.63529414 0.57254905 0.5137255 ]
   [0.63529414 0.57254905 0.5137255 ]
   [0.63529414 0.57254905 0.5137255 ]
   ...
   [0.18431373 0.18823531 0.16862746]
   [0.17254902 0.1764706  0.15686275]
   [0.17254902 0.1764706  0.15686275]]

  ...

  [[0.6862745  0.64705884 0.60784316]
   [0.6862745  0.64705884 0.60784316]
   [0.6862745  0.64705884 0.60784316]
   ...
   [0.29803923 0.35686275 0.38431376]
   [0.2901961  0.34117648 0.37254903]
   [0.28627452 0.3372549  0.36862746]]

  [[0.68235296 0.6431373  0.6039216 ]
   [0.6862745  0.64705884 0.60784316]
   [0.6862745  0.64705884 0.60784316]
   ...
   [0.30588236 0.3647059  0.3921569 ]
   [0.29411766 0.34509805 0.37647063]
   [0.27450982 0.3254902  0.35686275]]

  [[0.6862745  0.64705884 0.60784316]
   [0.68235296 0.6431373  0.6039216 ]
   [0.68235296 0.6431373  0.6039216 ]
   ...
   [0.2901961  0.34901962 0.37647063]
   [0.28235295 0.33333334 0.3647059 ]
   [0.2784314  0.32941177 0.36078432]]]


 [[[0.10196079 0.10196079 0.09411766]
   [0.10980393 0.10980393 0.10196079]
   [0.09803922 0.09803922 0.09019608]
   ...
   [0.39607847 0.25490198 0.12156864]
   [0.4039216  0.2627451  0.12941177]
   [0.427451   0.25882354 0.1254902 ]]

  [[0.09803922 0.09803922 0.09019608]
   [0.10588236 0.10588236 0.09803922]
   [0.09803922 0.09803922 0.09019608]
   ...
   [0.427451   0.27450982 0.14509805]
   [0.43529415 0.28235295 0.15294118]
   [0.454902   0.2784314  0.14901961]]

  [[0.09411766 0.09411766 0.08627451]
   [0.09803922 0.09803922 0.09019608]
   [0.09803922 0.09803922 0.09019608]
   ...
   [0.454902   0.28627452 0.14901961]
   [0.45882356 0.2901961  0.15294118]
   [0.47450984 0.29411766 0.15294118]]

  ...

  [[0.06666667 0.05882353 0.07058824]
   [0.18039216 0.1764706  0.16862746]
   [0.5686275  0.5411765  0.4784314 ]
   ...
   [0.5568628  0.43137258 0.24705884]
   [0.5568628  0.43137258 0.24705884]
   [0.5529412  0.43137258 0.24705884]]

  [[0.06666667 0.05882353 0.07058824]
   [0.18039216 0.1764706  0.16862746]
   [0.56078434 0.53333336 0.47058827]
   ...
   [0.5568628  0.43137258 0.24705884]
   [0.5568628  0.43137258 0.24705884]
   [0.5529412  0.43137258 0.24705884]]

  [[0.06666667 0.05882353 0.07058824]
   [0.18039216 0.1764706  0.16862746]
   [0.5529412  0.5254902  0.46274513]
   ...
   [0.5568628  0.43137258 0.24705884]
   [0.5568628  0.43137258 0.24705884]
   [0.5529412  0.43137258 0.24705884]]]


 [[[0.78823537 0.79215693 0.8000001 ]
   [0.7960785  0.8000001  0.8078432 ]
   [0.7843138  0.78823537 0.7960785 ]
   ...
   [0.73333335 0.74509805 0.76470596]
   [0.74509805 0.7490196  0.7686275 ]
   [0.74509805 0.7490196  0.7686275 ]]

  [[0.7803922  0.7843138  0.79215693]
   [0.7686275  0.7725491  0.7803922 ]
   [0.78823537 0.79215693 0.8000001 ]
   ...
   [0.76470596 0.77647066 0.7960785 ]
   [0.7568628  0.7607844  0.7803922 ]
   [0.7568628  0.7607844  0.7803922 ]]

  [[0.79215693 0.7960785  0.80392164]
   [0.7960785  0.8000001  0.8078432 ]
   [0.79215693 0.7960785  0.80392164]
   ...
   [0.73333335 0.74509805 0.76470596]
   [0.7372549  0.7411765  0.7607844 ]
   [0.7607844  0.76470596 0.7843138 ]]

  ...

  [[0.8352942  0.83921576 0.8196079 ]
   [0.82745105 0.8313726  0.8000001 ]
   [0.8352942  0.8431373  0.79215693]
   ...
   [0.7960785  0.81568635 0.8000001 ]
   [0.7372549  0.7372549  0.7294118 ]
   [0.7960785  0.7960785  0.78823537]]

  [[0.85098046 0.85098046 0.8588236 ]
   [0.85098046 0.85098046 0.8431373 ]
   [0.85098046 0.8588236  0.81568635]
   ...
   [0.79215693 0.8117648  0.7960785 ]
   [0.79215693 0.79215693 0.7843138 ]
   [0.8078432  0.8078432  0.8000001 ]]

  [[0.81568635 0.8196079  0.78823537]
   [0.8235295  0.82745105 0.80392164]
   [0.86666673 0.86666673 0.8588236 ]
   ...
   [0.8078432  0.7843138  0.7843138 ]
   [0.81568635 0.8117648  0.7960785 ]
   [0.8000001  0.7960785  0.7803922 ]]]


 ...


 [[[0.01176471 0.00392157 0.00784314]
   [0.01176471 0.00392157 0.00784314]
   [0.01176471 0.00392157 0.00784314]
   ...
   [0.04705883 0.01568628 0.00784314]
   [0.04313726 0.01176471 0.00392157]
   [0.04705883 0.         0.        ]]

  [[0.01176471 0.00392157 0.00784314]
   [0.01176471 0.00392157 0.00784314]
   [0.01176471 0.00392157 0.00784314]
   ...
   [0.03921569 0.         0.        ]
   [0.03529412 0.         0.        ]
   [0.04705883 0.         0.        ]]

  [[0.01176471 0.00392157 0.00784314]
   [0.01176471 0.00392157 0.00784314]
   [0.01176471 0.00392157 0.00784314]
   ...
   [0.0509804  0.01176471 0.00784314]
   [0.04705883 0.00784314 0.00392157]
   [0.04705883 0.         0.        ]]

  ...

  [[0.41176474 0.38823533 0.38823533]
   [0.32156864 0.29803923 0.29803923]
   [0.38823533 0.36862746 0.35686275]
   ...
   [0.58431375 0.62352943 0.5882353 ]
   [0.5921569  0.6156863  0.6       ]
   [0.5254902  0.5411765  0.5529412 ]]

  [[0.36078432 0.34117648 0.32941177]
   [0.2784314  0.25490198 0.25490198]
   [0.36078432 0.3372549  0.34509805]
   ...
   [0.59607846 0.63529414 0.5921569 ]
   [0.5882353  0.6039216  0.6       ]
   [0.5411765  0.5529412  0.57254905]]

  [[0.40784317 0.38823533 0.37254903]
   [0.35686275 0.33333334 0.33333334]
   [0.36862746 0.34509805 0.36078432]
   ...
   [0.5764706  0.6039216  0.57254905]
   [0.53333336 0.5372549  0.5529412 ]
   [0.47450984 0.48627454 0.5137255 ]]]


 [[[0.8196079  0.8235295  0.69803923]
   [0.8235295  0.8196079  0.69803923]
   [0.8235295  0.8196079  0.69803923]
   ...
   [0.7686275  0.7568628  0.63529414]
   [0.76470596 0.75294125 0.6313726 ]
   [0.76470596 0.75294125 0.6313726 ]]

  [[0.8235295  0.8196079  0.69803923]
   [0.8235295  0.8196079  0.69803923]
   [0.8235295  0.8196079  0.69803923]
   ...
   [0.7686275  0.7568628  0.63529414]
   [0.7686275  0.7568628  0.63529414]
   [0.76470596 0.75294125 0.6313726 ]]

  [[0.8235295  0.8196079  0.7019608 ]
   [0.8235295  0.8196079  0.7019608 ]
   [0.8235295  0.8196079  0.7019608 ]
   ...
   [0.7686275  0.7568628  0.63529414]
   [0.7686275  0.7568628  0.63529414]
   [0.7686275  0.7568628  0.63529414]]

  ...

  [[0.35686275 0.25882354 0.17254902]
   [0.37254903 0.27450982 0.18823531]
   [0.41960788 0.31764707 0.227451  ]
   ...
   [0.654902   0.6        0.54901963]
   [0.654902   0.6        0.54901963]
   [0.65882355 0.6039216  0.5529412 ]]

  [[0.35686275 0.25882354 0.17254902]
   [0.3372549  0.2392157  0.15294118]
   [0.36078432 0.25882354 0.16862746]
   ...
   [0.6666667  0.6117647  0.56078434]
   [0.6627451  0.60784316 0.5568628 ]
   [0.6666667  0.6117647  0.56078434]]

  [[0.35686275 0.25882354 0.17254902]
   [0.3254902  0.227451   0.14117648]
   [0.34117648 0.2392157  0.14901961]
   ...
   [0.6666667  0.6117647  0.56078434]
   [0.6666667  0.6117647  0.56078434]
   [0.65882355 0.6039216  0.5529412 ]]]


 [[[0.48627454 0.54509807 0.5568628 ]
   [0.45098042 0.5019608  0.53333336]
   [0.3254902  0.37254903 0.41960788]
   ...
   [0.6039216  0.60784316 0.6156863 ]
   [0.69803923 0.7019608  0.7176471 ]
   [0.61960787 0.6156863  0.63529414]]

  [[0.44705886 0.5058824  0.5176471 ]
   [0.39607847 0.44705886 0.4784314 ]
   [0.35686275 0.39607847 0.4431373 ]
   ...
   [0.50980395 0.5294118  0.54509807]
   [0.4156863  0.427451   0.454902  ]
   [0.5058824  0.5058824  0.5372549 ]]

  [[0.4431373  0.49411768 0.5176471 ]
   [0.34117648 0.3921569  0.42352945]
   [0.3647059  0.4039216  0.4431373 ]
   ...
   [0.38431376 0.4156863  0.45882356]
   [0.40000004 0.42352945 0.47058827]
   [0.49803925 0.52156866 0.5686275 ]]

  ...

  [[0.14901961 0.14509805 0.12941177]
   [0.16470589 0.16078432 0.14509805]
   [0.15686275 0.15294118 0.13725491]
   ...
   [0.45098042 0.5294118  0.57254905]
   [0.32156864 0.38823533 0.427451  ]
   [0.41960788 0.45882356 0.49411768]]

  [[0.18431373 0.18039216 0.16470589]
   [0.16470589 0.16078432 0.14509805]
   [0.14117648 0.13725491 0.12156864]
   ...
   [0.3921569  0.4784314  0.5294118 ]
   [0.427451   0.49411768 0.53333336]
   [0.37254903 0.40784317 0.4431373 ]]

  [[0.18039216 0.1764706  0.16078432]
   [0.16470589 0.16078432 0.14509805]
   [0.17254902 0.16862746 0.15294118]
   ...
   [0.3372549  0.42352945 0.4784314 ]
   [0.31764707 0.37254903 0.4156863 ]
   [0.5019608  0.5294118  0.56078434]]]]